include rose-pine-moon.conf

cursor white

cursor_trail 10
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 0

cursor_blink_interval 0.5

hide_window_decorations titlebar-only
window_padding_width 10
background_opacity 0.85
background_blur 30

sync_to_monitor yes

font_family JetBrainsMono Nerd Font Mono
font_size 11.0
shell /opt/homebrew/bin/fish --login

